spring.config.import=optional:secrets.properties

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager

server.servlet.context-path=/api/v1